const skills = [
  { title: "Frontend", items: ["React", "JavaScript", "TypeScript", "HTML5", "CSS3"] },
  { title: "UI & Calidad", items: ["Responsive Design", "Accessibility", "Component Systems", "Git"] },
  { title: "Por confirmar", items: ["Frameworks adicionales", "Testing", "Backend / APIs", "Herramientas de diseño"], pending: true },
];
const projects = [1, 2, 3];

export default function Home() {
  return <main>
    <nav className="nav" aria-label="Navegación principal">
      <a className="brand" href="#top" aria-label="Inicio — Sebastian"><span>SS</span><strong>Sebastian.</strong></a>
      <div className="navLinks"><a href="#about">Perfil</a><a href="#skills">Skills</a><a href="#projects">Proyectos</a><a href="#experience">Trayectoria</a><a className="navCta" href="#contact">Hablemos</a></div>
    </nav>
    <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow"><span /> Disponible para nuevas oportunidades</p><h1>Construyo experiencias digitales que <em>se sienten bien.</em></h1><p className="lede">Soy Sebastian, developer enfocado en crear interfaces modernas, claras y accesibles con React.</p><div className="heroActions"><a className="primaryButton" href="#projects">Ver mi trabajo <span aria-hidden="true">↘</span></a><a className="textLink" href="#contact">Contactarme <span aria-hidden="true">→</span></a></div></div><aside className="profileCard" aria-label="Resumen de perfil"><div className="availability"><i /> Open to work</div><div className="monogram" aria-hidden="true">S</div><p>Frontend Developer</p><div className="cardMeta"><span>React</span><span>Responsive UI</span><span>Accessibility</span></div></aside></section>
    <div className="scrollCue"><span>Explorar perfil</span><i /></div>
    <section className="section about" id="about"><div className="sectionLabel"><span>01</span> Perfil</div><div className="aboutContent"><p className="bigStatement">Código limpio. Interfaces intuitivas. <em>Productos que conectan.</em></p><div className="aboutText"><p>Me interesa transformar ideas en experiencias web cuidadas, rápidas y fáciles de usar. Mi enfoque combina desarrollo frontend con atención al detalle visual.</p><p className="placeholderNote"><strong>Perfil en construcción:</strong> agrega aquí tus años de experiencia, especialidad, industria preferida y el tipo de equipo donde quieres aportar.</p></div></div></section>
    <section className="section skillsSection" id="skills"><div className="sectionLabel light"><span>02</span> Habilidades</div><div className="sectionHeading"><div><p className="kicker">Mi toolkit</p><h2>Con qué construyo</h2></div><p>Herramientas y prácticas enfocadas en crear productos web mantenibles y de alta calidad.</p></div><div className="skillGrid">{skills.map((group,index)=><article className={group.pending?"skillCard pending":"skillCard"} key={group.title}><span className="cardNumber">0{index+1}</span><h3>{group.title}</h3><ul>{group.items.map(item=><li key={item}>{item}{group.pending&&<small> completar</small>}</li>)}</ul></article>)}</div></section>
    <section className="section projects" id="projects"><div className="sectionLabel"><span>03</span> Proyectos</div><div className="sectionHeading dark"><div><p className="kicker">Trabajo seleccionado</p><h2>Proyectos que hablan por mí</h2></div><p>Este espacio está preparado para casos reales. Cada tarjeta debe explicar el problema, tu solución y el impacto.</p></div><div className="projectGrid">{projects.map(project=><article className="projectCard" key={project}><div className={`projectVisual visual${project}`}><span>Proyecto {String(project).padStart(2,"0")}</span><div className="mockWindow"><i/><i/><i/></div></div><div className="projectInfo"><div><p>React · Frontend</p><h3>Nombre del proyecto</h3></div><span className="projectArrow" aria-hidden="true">↗</span></div><p className="projectDescription">Reemplaza este texto con una descripción breve del reto, tu contribución y el resultado obtenido.</p><span className="placeholderTag">Contenido por completar</span></article>)}</div></section>
    <section className="section journey" id="experience"><div className="sectionLabel"><span>04</span> Trayectoria</div><div className="journeyGrid"><div><p className="kicker">Experiencia</p><h2>Donde he aportado</h2></div><div className="timeline"><article><span className="timelineDot"/><div><p>Fecha — Fecha</p><h3>Cargo / Rol</h3><h4>Empresa u organización</h4><p className="muted">Agrega 2–3 logros medibles, tecnologías utilizadas y el impacto de tu trabajo.</p><span className="placeholderTag">Experiencia por completar</span></div></article><article><span className="timelineDot"/><div><p>Fecha — Fecha</p><h3>Cargo / Rol anterior</h3><h4>Empresa u organización</h4><p className="muted">Describe responsabilidades relevantes para el puesto que estás buscando.</p><span className="placeholderTag">Experiencia por completar</span></div></article></div></div></section>
    <section className="section education" id="education"><div className="sectionLabel"><span>05</span> Formación</div><div className="educationCard"><div className="eduIcon" aria-hidden="true">⌁</div><div><p className="kicker">Educación</p><h2>Título o programa académico</h2><p>Institución educativa · Año</p></div><span className="placeholderTag">Información por completar</span></div></section>
    <section className="contact" id="contact"><p className="kicker">¿Construimos algo juntos?</p><h2>Convirtamos una buena idea en una <em>gran experiencia.</em></h2><p>Estoy abierto a oportunidades frontend, colaboraciones y conversaciones con equipos que valoran el trabajo bien hecho.</p><a className="contactButton" href="mailto:tu-email@ejemplo.com" aria-label="Enviar correo a Sebastian; dirección temporal por completar">Escríbeme <span>↗</span></a><p className="contactPlaceholder">Reemplazar con email real · Agregar LinkedIn · Agregar GitHub</p></section>
    <footer><a className="brand footerBrand" href="#top"><span>SS</span><strong>Sebastian.</strong></a><p>Frontend Developer · Portfolio</p><a href="#top">Volver arriba ↑</a></footer>
  </main>;
}
